### ISSUE TITLE
Minor issues brining plugins into SWProxy

### ISSUE THREAD

**Issue by ghost** [lstern/SWProxy-plugins#1]
I'm on SWProxy master, to get the plugins to load i had to remove

"plugins" parameter from process_request i.e fulllogger.py,

and change **import SWPlugin** to **from SWPlugin import SWPlugin**

without doing this, the plugins just wouldnt load, any clues why? I've got them loading now, considering issuing a pull request.

Are they working locally for your SWProxy? Have you backported from master into your fork?

**Comment by fperegrinvs** [comment]
Sorry about that. They were working for me locally but my master wasn't up-to-date. The process_request method was changed 8 days ago and my plugins weren't updated.  

No sure why you had to change the import tho.
