### ISSUE TITLE
How do I contribute?

### ISSUE THREAD

**Issue by dozens** [lstern/SWProxy-plugins#16]
I have some code that I have been using and converting it to plugins so I can continue to pull from main line SWProxy. Can someone post a cheatsheet of git commands to contribute new files, etc.

If it matters I am developing on a mac and have the git tools installed.

**Comment by lstern** [comment]
add me on line, my id is fperegrinus

**Comment by fperegrinvs** [comment]
http://code.tutsplus.com/tutorials/how-to-collaborate-on-github--net-34267
