### ISSUE TITLE
Use DictUnicodeWriter to record logs

### ISSUE THREAD

**Issue by fperegrinvs** [lstern/SWProxy-plugins#20]
So its easier to save the logs  in other formats

**Comment by daniellhotka** [comment]
So if I understand this correctly, you want to change the:

```
fr.write(log_entry)
fr.write('\n')
```

for another method, or would the revamp include the way that the log_entry variable is assembled?

**Comment by fperegrinvs** [comment]
Revamp, like the [visit plugin](https://github.com/kakaroto/SWProxy/blob/master/plugins/GenerateVisitFriend.py)

**Comment by daniellhotka** [comment]
So I've done the refactor for the SummonLogger, however I have this strange discrepancy. 

If I use this code, it executes up until the point where the DictUnicodeWriter kicks in at the end of the script (as expected given the way it's called) and prints "Hello I'm working" for every single request whether it's a summon or not.

```
import json
import os
import time
from SWParser import *
import SWPlugin
import threading

... an array and formula ...

class SummonLogger(SWPlugin.SWPlugin):
    def __init__(self):
        with open('swproxy.config') as f:
            self.config = json.load(f)

    def process_request(self, req_json, resp_json):
        config = self.config
        print "Hello I'm working"
        if 'log_summon' not in config or not config['log_summon']:
            return

        command = req_json['command']
        if command == 'SummonUnit':
            return self.log_summon(req_json, resp_json, config)

```

If I use this code, the print never shows up (which it should for every single request made) and nothing is logged

```
import json
import os
import time
from SWParser import *
from SWPlugin import SWPlugin
import threading

... an array and formula ...

class SummonLogger(SWPlugin):
    def __init__(self):
        with open('swproxy.config') as f:
            self.config = json.load(f)

    def process_request(self, req_json, resp_json):
        config = self.config
        print "Hello I'm working"
        if 'log_summon' not in config or not config['log_summon']:
            return

        command = req_json['command']
        if command == 'SummonUnit':
            return self.log_summon(req_json, resp_json, config)
```

I have no idea what is so wrong with the 2nd code it never works as it passes the loading check for formulas/indents/etc and is shown as running. I have attached the complete file that doesn't work in a .txt format so it lets me upload.

[SummonLogger.txt](https://github.com/lstern/SWProxy-plugins/files/210546/SummonLogger.txt)
