### ISSUE TITLE
TOA logger

### ISSUE THREAD

**Issue by fperegrinvs** [lstern/SWProxy-plugins#21]
time, stage, difficulty, win-loss clear time, team, final boss

**Comment by daniellhotka** [comment]
Neither the Start nor Result json contain the unit_master_id of the monsters used in the battle, just their unique unit_id. This same problem exists in Arena losses and could also pop up in other places. 

At first I though caching part of the login block would solve this but maybe it is easier to create a global function that opens the <wizard_id>.json file created on login and searches inside it for the info needed?

**Comment by daniellhotka** [comment]
And now I went back and read the Arena thread and that's what you had suggested lol

So maybe we need to write another plugin that creates a json with a dictionary that is exclusively {'unit_id' : 'unit_master_id', ... } or add some more info like lvl, grade and awakened status?

**Comment by fperegrinvs** [comment]
While a smaller json would be great,every plugin is independent and adding
plugin dependencies would be a bad move. We can just move the json reading
to the init section and store inside the config object.

**Comment by daniellhotka** [comment]
ok, I saw what you did with the world boss and I'm adapting it for ToA since that's fast, then I'll move to Arena

**Comment by daniellhotka** [comment]
![image](https://cloud.githubusercontent.com/assets/17763294/14405266/5cbbb676-fe61-11e5-9091-de122b2467b6.png)

Do you think I should add a column holding boss/enemy names if applicable?

**Comment by fperegrinvs** [comment]
I would add 4 columns with the name of the last wave mobs.
