### ISSUE TITLE
Arena Logger

### ISSUE THREAD

**Issue by fperegrinvs** [lstern/SWProxy-plugins#22]
Time, match duration, win-loss, opponent name, teams,

**Comment by daniellhotka** [comment]
can't find the opponent name anywhere, only their ID

**Comment by fperegrinvs** [comment]
You need to cache this info from the GetArenaWizardList response.

**Comment by daniellhotka** [comment]
and from GetArenaLog for revenges

**Comment by daniellhotka** [comment]
do you think we should include the rivals? or just filter them out?

**Comment by fperegrinvs** [comment]
include

**Comment by daniellhotka** [comment]
I'm very close to finishing, however my problem is that the plugin_data generated by GetArenaLog and GetArenaWizardList is not getting passed on to log_end_battle. 
On the other hand, the plugin_data from BattleArenaStart info is passed on fine. 
Not sure what I need to do differently for it to get passed along as well.

```
    def process_request(self, req_json, resp_json):
        config = self.config
        if 'log_arena' not in config or not config['log_arena']:
            return

        command = req_json['command']
        if command == 'GetArenaLog':
            if 'arena-logger-data' not in config:
                config['arena-logger-data'] = {}

            plugin_data = config['arena-logger-data']
            wizard_id = str(req_json['wizard_id'])
            revenge_list = {}
            for opp in resp_json['arena_log']:
                revenge_list[str(opp['wizard_id'])] = opp['wizard_name']
            plugin_data[wizard_id] = {'revenge_list' : revenge_list}

        if command == 'GetArenaWizardList':
            if 'arena-logger-data' not in config:
                config['arena-logger-data'] = {}

            plugin_data = config['arena-logger-data']
            wizard_id = str(req_json['wizard_id'])
            arena_list = {}
            for opp in resp_json['arena_list']:
                arena_list[str(opp['wizard_id'])] = opp['wizard_name']
            plugin_data[wizard_id] = {'arena_list' : arena_list}

        if command == 'BattleArenaStart':
            if 'arena-logger-data' not in config:
                config['arena-logger-data'] = {}

            plugin_data = config['arena-logger-data']
            wizard_id = str(req_json['wizard_id'])
            start = int(time.time())
            opp_monster_list = {}
            for opp_mon in resp_json['opp_unit_list']:
                opp_monster_list[opp_mon['pos_id']] = opp_mon['unit_info']['unit_master_id']
            opponent_id = resp_json['opp_pvp_info']['wizard_id']
            plugin_data[wizard_id] = {'start' : start, 'opp_monster_list' : opp_monster_list, 'opponent_id' : opponent_id}

        if command == 'BattleArenaResult':
            return self.log_end_battle(req_json, resp_json, config)
```

**Comment by daniellhotka** [comment]
Now that the basics are in place, I'll add the rival section, which might be kind of large because their monsters have different master ids than normal monsters.
On the other hand, do you think we should add the lvl and grade of monsters or just leave it at their name?

**Comment by daniellhotka** [comment]
Just noticed that when you lose a battle, your own monsters are not recorded because their master_ids are not anywhere to be found in the ArenaStart nor ArenaResult if there is a loss. The only thing usable is the unit_id which is the unique id for each monster ever summoned. Not sure how to sort out this discrepancy unless we cache the login block which has all the monster's info.

**Comment by fperegrinvs** [comment]
Maybe we don't need to cache, but just read the login json or create a
smaller json for better performance. This is getting tricky ...

**Comment by fperegrinvs** [comment]
https://github.com/lstern/SWProxy-plugins/blob/master/plugins/WorldBossLogger.py#L21
