### ISSUE TITLE
GW logger

### ISSUE THREAD

**Issue by fperegrinvs** [lstern/SWProxy-plugins#23]
time,match duration, win/loss (2R), teams

**Comment by kakaroto** [comment]
I think the one mentioned in https://github.com/kakaroto/SWProxy/issues/76 is for dumping the existing server-side log from the json into a csv format rather than logging actual runs.

**Comment by fperegrinvs** [comment]
Yeah, I'm working on this

**Comment by Anacondych** [comment]
Actually I've meant to generate .csv log from Guild Battle Log 
![log](https://cloud.githubusercontent.com/assets/18255313/22546077/1e39e584-e944-11e6-95a2-1deb91bb9973.jpg)
  for all guildmates battles (not only mine) together with GuildPoints Acquired in following format:
 Date, Enemy Guild, Opponent, Round 1 (Loss/Win), Round 2 (Loss/Win), Guild Points Acquired.
