### ISSUE TITLE
Rune Optimizer Live Integration

### ISSUE THREAD

**Issue by fperegrinvs** [lstern/SWProxy-plugins#26]
Every action will generate a json file that will be stored on a predetermined folder

**Comment by fperegrinvs** [comment]
Action that will generate a json :

Get new rune (drop or shop)
Sell rune
Upgrade rune
Equip rune
Remove rune (unequip)
Grindstone/Enchant  rune
Sell craft
new craft

Should we include mob changes (levelup, awaken, etc) ? I guess this should be V2

**Comment by Xzandro** [comment]
Yeah, we should process the above event first and maybe in later version we can go further.

**Comment by fperegrinvs** [comment]
I'll post the jsons from com2us, so we can decide on our json format

**Comment by Xzandro** [comment]
Okay

**Comment by Xzandro** [comment]
In general that should be in the json object for every event: {time: timestamp, action: action}

**Comment by fperegrinvs** [comment]
Some events have one rune, others have multiple runes (sell rune). Maybe we
could use this structure for all events:

{time: timestamp, action: action, runes:[{...complete rune1 data...},{...
complete rune2 data ...}]}

**Comment by Xzandro** [comment]
Okay. sounds good. for equip you have one rune and one monster I suppose?

**Comment by fperegrinvs** [comment]
Correct!
