### ISSUE TITLE
GoogleSheetWriter Traceback

### ISSUE THREAD

**Issue by J-Saas** [lstern/SWProxy-plugins#29]
Hello!
I've been trying to figure out of an error I've been having as of late with GoogleSheetWriter.

`2016-04-06 12:58:26,528: yapsy - ERROR - Unable to import plugin: C:\Users\Konamiya\Desktop\SWProxy\plugins\GoogleSheetWriter
Traceback (most recent call last):
  File "site-packages\yapsy\PluginManager.py", line 488, in loadPlugins
  File "C:\Users\Konamiya\Desktop\SWProxy\plugins\GoogleSheetWriter.py", line 2, in <module>
    import gspread
ImportError: No module named gspread`

I've not noticed this error before but at the end of the file it's clearly able to connect to google anyway?

`2016-04-06 13:07:54,565: proxy - INFO - 192.168.0.163:59801 - CONNECT android.googleapis.com:443
2016-04-06 13:07:54,957: proxy - INFO - 192.168.0.163:59802 - CONNECT www.google.no:443`

I'm not sure what's going on with it. 
I'm using 64-bit version though, but I don't think that should matter. Image of python/gspread version.
http://i.imgur.com/2kqCA19.png

Any idea what's going on here?

**Comment by fperegrinvs** [comment]
GoogleSheetWriter is not an official plugin yet. It requires gspread so it won't work with the swproxy exe. You need to run from python (after pip installing gspread) or create a custom build of swproxy packages gspread.
