### ISSUE TITLE
SWProxy Failed to Connect

### ISSUE THREAD

**Issue by dataeraser** [lstern/SWProxy-plugins#36]
I get a Failed to connected with the network. Please try again later. Error.

Here's my stats: Laptop on home, private network. Router is a Netgear Nighthawk R7000 (one of those $150+ routers with the 3 antennaes) 
I right clicked the Norton Icon in my system tray and clicked Disable Auto-Protect and Disable Smart Firewall.
 I have Windows 10, upgraded from windows 7 I am the only user on this laptop.
 I right clicked SWProxy file and ran it normally and also ran it as administrator.
 I typed in the IP address and port 8080 exactly into my iphone 6 WiFi settings (most up to date version of iOS). 
I hit Start Proxy. Nothing changes on the black dos screen. 
I open the game on my phone. 
It says tap to start I tap It shows Checking For Updates Then immediately shows the Failed to connect error.

I have reset my router and tried turning the wifi on and off on my phone. I do not get any messages that lead up to a friend list. It just stops.

I have also noticed that no internet connections at all work on my phone now. However, the WifI icon still shows on my phone.

**Comment by fperegrinvs** [comment]
check this: https://github.com/kakaroto/SWProxy/issues/83
