### ISSUE TITLE
SummonLogger new button x10

### ISSUE THREAD

**Issue by KilluaFein** [lstern/SWProxy-plugins#38]
The summonlogger only recognize the first monster of the x10 batch

`2016-05-17 10:20,Unknown Scroll,Mimick,Water,1,No`
`﻿2016-05-17 10:20,Unknown Scroll,Mushroom,Water,1,No`

**Comment by fperegrinvs** [comment]
@porksmash

**Comment by daniellhotka** [comment]
I've got a fix for the Logger, will be uploading shortly. Might have to fix the uploader plugin too
