### ISSUE TITLE
Rune Efficiency values

### ISSUE THREAD

**Issue by daddyrubin** [lstern/SWProxy-plugins#41]
I noticed that there is a difference in the values of the Barion's Rune efficiency, current and max potential.  There are some where Barion's, which i would assume would be the lowest value because its how it is currently is higher than the current potential, and some where the current potential is higher than the max potential.  

This may be correct and I am not understanding the values properly.  If it is correct could someone explain what the values mean exactly?  I was about to sell all under a 70% potential but noticed the differences.

**Comment by fperegrinvs** [comment]
Its a different formula based on Barion's Rune Efficiency.  Some differences:  we don't ignore flat subs (but penalize them), slightly different parameters for 1/3/5 and 2/4/6 slots because for odd slots, the main stat will have a lower impact on overall rune quality (main vs subs).

**Comment by daddyrubin** [comment]
Ok thank you for your fast response. So if I'm looking to sell all runes in my inventory under a certain %, would you recommend using the max potential value?

**Comment by fperegrinvs** [comment]
Not really. While the max potential value would give you the rune overall
quality it won't tell you anything about rune usefulness. A rune with good
attack, defense and res subs may be worse than a rune with average atk,
speed and cr subs. You also need to account for grindstones .. not every
sub is grindstonable. Its also possible to replace a bad sub using a
enchant stone.  I'm drafting a new formula to evaluate runes to include the
aforementioned points.
