### ISSUE TITLE
Invalid Format error

### ISSUE THREAD

**Issue by daddyrubin** [lstern/SWProxy-plugins#44]
I am getting Invalid Format errors while running the parser.

**Comment by AizenSousuke** [comment]
Yeap. Still facing that error.

**Comment by msteudel** [comment]
I believe this has been fixed, try downloading latest version and see if that helps.

**Comment by daddyrubin** [comment]
I'm not getting the Invalid Format error now, but it is hanging before it gets to the "connecting to server" part of the login.  I tried the starting with the proxy off when I start the game then switching it on before it connects to server but that did not get my files loaded with monsters and runes.  

![image](https://cloud.githubusercontent.com/assets/18055418/16064727/c58f5344-3271-11e6-9e02-a9afd6e66152.png)
