### ISSUE TITLE
How to get files to be written out?

### ISSUE THREAD

**Issue by msteudel** [lstern/SWProxy-plugins#45]
I have both the SWPRoxy-plugins and SWProxy running on my machine (not at the same time). I was wondering why the swproxy-plugins doesn't write out any files. I enabled full logs and I can see it grabbing all the json , but I can't figure out where it's writing the optimizer and swafarm files out too. Is there a setting I need to change to enable this? I'm using the cli version of the code. And I'm downloading it directly from github vs downloading the releases.

**Comment by mason2882** [comment]
I'm able to connect to the proxy and the it shows all of files being made.  However, no .json files are created in the folder.

**Comment by fperegrinvs** [comment]
windows or macos ? (maybe you compiled from the source...)

**Comment by msteudel** [comment]
Im on a mac

**Comment by mason2882** [comment]
I'm on Windows 10

**Comment by cdmichaelb** [comment]
On windows 10, also having the same problem. Folder is empty except full-log.txt and the basic program files.

Full-log is properly populated.

Edit: Relaunched the proxy a few times and it started working correctly.
