### ISSUE TITLE
after all of setup..nothing happen..

### ISSUE THREAD

**Issue by strikerogue** [lstern/SWProxy-plugins#46]
hello..
i run sw proxy latest release in windows 10..after insert all of proxy setting in my phone n started the program, nothing happened,sw proxy cant get sw data from my phone..how to fix this? thanks

**Comment by hugo4566** [comment]
Same issue here. The problem returned after SW update.

**Comment by ghost** [comment]
Asia-Server?

**Comment by hugo4566** [comment]
Asia server D:

**Comment by ghost** [comment]
https://github.com/kakaroto/SWProxy/pull/119

I hope this will help

**Comment by ragnar73** [comment]
Hi, I'm on Asia server too, I tried the fix you posted, it went for a while, then it said there was an error in the proxy.py file... maybe have to change the server name there too?

**Comment by ghost** [comment]
Yes sry my fail :/ (im on EU so i missed it :/)

https://github.com/kakaroto/SWProxy/pull/121

**Comment by fperegrinvs** [comment]
Not sure if its the right fix. Can someone test it ?

**Comment by ragnar73** [comment]
Yeah, now it works great, thanks! :)

**Comment by fuggin** [comment]
I am have issues on global. it have been a few months since I used it. tried Friday night and it either gave me a timed out err. or loaded but did not send data. am I the only one?

**Comment by ghost** [comment]
Did und Download the last release?

@ragnar73

Did it work after the pull request 119 or is the change from 121 needed to work?

**Comment by fuggin** [comment]
not sure if i have the last version or not will check when i get home. jasper cole 

```
On Monday, June 27, 2016 11:04 AM, Viper2k4 <notifications@github.com> wrote:
```

 Did und Download the last release?@ragnar73Did it work after the pull request 119 or is the change from 121 needed to work?—

**Comment by strikerogue** [comment]
@Viper2k4 what should i do with that code sheet?

**Comment by ghost** [comment]
https://github.com/lstern/SWProxy-plugins/releases

Download it and try it. And plz report if it work or not. And are u on Asia or Global?

**Comment by fuggin** [comment]
viper witch one the latest or the pre. i am on global jasper cole 

```
On Monday, June 27, 2016 1:33 PM, Viper2k4 <notifications@github.com> wrote:
```

 https://github.com/lstern/SWProxy-plugins/releasesDownload it and try it. And plz report if it work or not. And are u on Asia or Global?—

**Comment by ghost** [comment]
The most top one :)

**Comment by fuggin** [comment]
ok was just hesitant with it saying asia on it.  jasper cole 

```
On Monday, June 27, 2016 2:24 PM, Viper2k4 <notifications@github.com> wrote:
```

 The most top one :)—

**Comment by fuggin** [comment]
because i am in golbal

**Comment by ghost** [comment]
Its only a fix for Asia. Because it should normaly work on EU, Global and so on.

**Comment by fuggin** [comment]
thank you, jasper cole 

```
On Monday, June 27, 2016 2:49 PM, Viper2k4 <notifications@github.com> wrote:
```

 Its only a fix for Asia. Because it should normaly work on EU, Global and so on.—

**Comment by fuggin** [comment]
got it working thanks Viper

**Comment by fuggin** [comment]
Viper I thought I saw a page to do a donation can you like me that? so I can get a little extra time in

**Comment by fuggin** [comment]
getting that timed out error again. should I delete and reinstall?
