### ISSUE TITLE
EU server. Nothing happens.

### ISSUE THREAD

**Issue by danguedes** [lstern/SWProxy-plugins#47]
Hi there.
First of all, i appreciate everything you guys have done.
Now lets go for my issue.
I downloaded the last release for android, not the Asia Server because i play on EU server.
All right, everything set, proxy on swproxy, phone and wifi. Then i started the game and nothing happend. All i see is the message "proxy is running". 
How to fix it?

Thanks in advance.

Sry if its a repeated question. But i really didnt see it.

**Comment by fperegrinvs** [comment]
Have you every used SWProxy before ?

**Comment by danguedes** [comment]
Yes. The last FRR i did.

**Comment by fperegrinvs** [comment]
try the latest version from SWProxy (0.100) and tell me if its working for you. (I'll update swproxy-plugins if its working)

**Comment by danguedes** [comment]
I´ll try it later, just saw the new release. But i cant use it while working.
asap i´ll let you know if its working

Thanks again

**Comment by danguedes** [comment]
Yeah it didnt work.
I tried with gui and also with a command line python. Nothing happens.
I also tried in 2 different computers both windows (7 and 10).
Any tip?

**Comment by fperegrinvs** [comment]
whats your phone ?

**Comment by danguedes** [comment]
Sorry to take long.
I use a LG G3. But i used it before.

**Comment by danguedes** [comment]
Thx guys. My phone was the problem. Just change its ROM and it works
