### ISSUE TITLE
Doesn't log failed battle

### ISSUE THREAD

**Issue by KeqiLi** [lstern/SWProxy-plugins#49]
The swarfarm run logger doesn't log the failed battle with error message like:

SwarfarmLogger - Error: ['null value in column "dungeon_id" violates not-null constraint\n', 'DETAIL:  Failing row contains (392560, 2899748, 2016-07-09 01:23:30+00, 1, null, null, null, f, 00:00:39.218, 963, 0, null, null, null, null, 27541, 0).\n', ' null value in column "dungeon_id" violates not-null constraint\n', 'DETAIL:  Failing row contains (392560, 2899748, 2016-07-09 01:23:30+00, 1, null, null, null, f, 00:00:39.218, 963, 0, null, null, null, null, 27541, 0).\n']

**Comment by PeteAndersen** [comment]
I narrowed this down to failed scenarios only. Grab the latest plugin and give it a try
