### ISSUE TITLE
swarfarm logs don't seem to work

### ISSUE THREAD

**Issue by ghost** [lstern/SWProxy-plugins#57]
Got everything set up with the latest version and the proxy is running fine, no errors and the .csv logs are all created, but no logs are showing up at swarfarm personal logs.

**Comment by PeteAndersen** [comment]
Did you follow the directions under "How to Contribute" in the personal log section? There is an additional requirement in addition to the directions for global logs. 
https://swarfarm.com/data/log/mine/

**Comment by ghost** [comment]
Importing the -swarfarm.json? Yes, I've done that, got the ID associated with my account, tried it on my phone and tablet.

**Comment by PeteAndersen** [comment]
If your swarfarm account name is the same name as your github account, I can confirm the unique ID assigned by com2us is not associated with your swarfarm profile. Try importing one more time and let me know if there are any errors or issues during that process.

**Comment by ghost** [comment]
Yes, the name is the same. I did the import again, got the processing promt as well as the finalizing import page and after that the message that the import was successull.
I also did another dungeon run afterwards to see if something changed, but sadly doesn't looks like it.

**Comment by PeteAndersen** [comment]
Found it! My fault, an oversight when I switched user inventory to it's own table rather than being directly attached to the user profile table. Give me a minute and I will comment here again when the fix is live. Thank you for working through it with me.

**Comment by ghost** [comment]
No problem, and thank you for the great work you're doing =)

**Comment by PeteAndersen** [comment]
Alright, it's live. Try an import one more time and let me know when you've completed it and I'll confirm it's saving properly.

**Comment by ghost** [comment]
Alright, imported again.

**Comment by PeteAndersen** [comment]
Looks much better from my end. Logs should be working for you now.

**Comment by ghost** [comment]
Can confirm, it's working perfectly now. There's still a minor thing though: The contributions table at https://swarfarm.com/data/log/mine/ shows my dungeon runs not only on dungeons but at summons as well, while summons don't get displayed.

**Comment by PeteAndersen** [comment]
Fixed that as well, good catch. Closing this issue now.
