### ISSUE TITLE
optimizer.json missing?!

### ISSUE THREAD

**Issue by Nightreaver** [lstern/SWProxy-plugins#63]
Hello

I'm sorry to open an issue for this, but nowhere is mentioned where to get this file and all other plugins just mention that the file is missing. I tried accessing several places with my account, but the file doesn't show up

where/how do I get it?

**Comment by Nightreaver** [comment]
I see... even if it looks like the SWProxy is already included... its not... so still have to get these plugins too

why is it mixed up that much?

**Comment by Anathiel** [comment]
Hi everyone.
Since the topic is still opened i'll ask here..
Can someone explain the steps to get that .Json file please ?
I've used SWproxy and got the files created but I can't find the .json file nor the others .csv so.. yeah..
Please send help ? And praise the sun \[T ]/

**Comment by Nightreaver** [comment]
Download this version of SWProxy, once you did that - copy and paste the plugins from this repository to the one of "swproxy-plugins"

https://github.com/kakaroto/SWProxy

Only works if you have data from both...
