### ISSUE TITLE
SWProxy doesn't works Japan server

### ISSUE THREAD

**Issue by riona-l** [lstern/SWProxy-plugins#65]
hello.
I am not good at English but please forgive me.

I used swproxy until last month.
But I tried to use it yesterday but it did not move.
I tried the latest version but did not start up.
I compiled from the source but started up, but various data are not generated.
Data is not generated but the game starts.

os windows7Ult
phone GalaxyS5(AOS6)

Create a screen of logs when executed.
Is it possible to take more detailed logs?
I would appreciate it if you let me know if you know.

![swproxy](https://cloud.githubusercontent.com/assets/24364720/20864183/3326ae2c-ba29-11e6-9dc1-d9d3621597d9.jpg)

**Comment by fperegrinvs** [comment]
old ( see #67 )
