### ISSUE TITLE
Error 140001 - buggy last releases?

### ISSUE THREAD

**Issue by Xzandro** [lstern/SWProxy-plugins#68]
Hi, it seems that there is something wrong with the last release for some people. They get error 140001 if they want to start SWProxy. Her eis a reddit thread about this issue: https://www.reddit.com/r/summonerswar/comments/5jambp/global_swproxy_error_140001/

https://github.com/lstern/SWProxy-plugins/releases/tag/7 seems to work. I dont have the problem for any version so I cant really test it.

**Comment by tvcat** [comment]
Im having this problem too on 2 computers (win 7 and win 8.1).
release 7 is all good but the release after that including the latest release 102 is having the same error message

**Comment by fperegrinvs** [comment]
Can you confirm that version "0.99.5Q" is not working ?

**Comment by tvcat** [comment]
sorry. version "0.99.5Q is working

**Comment by fperegrinvs** [comment]
try to edit the swproxy.config file and change the line :  

 `   "disable_swarfarm_logger": false,
`
to

`    "disable_swarfarm_logger": true,
`
check if the program is working after this change

**Comment by Xzandro** [comment]
They probably should deactive swaglogger too, if you suspect some libaries to act weird. Or do you think that error is because of the overload of swarfarm? :o

**Comment by tvcat** [comment]
tried set to true but still not working.
the full error message is "Error loading Python DLL: C:\Users\user\AppData\Local\Temp\_MEI77762\python27.dl
l (error code 14001)"
i tried clearing the temp folder and it wont create any file in there.
i search a bit and found that some people suggest using --cleanup argument

**Comment by Gesshoku01** [comment]
yo guys. I have the same Issue with the python2 error 14001. Unistalled and reinstalled every library but still nothing. unlucky me/us. currently using with no issues v0.100. http://imgur.com/a/g4ThB all c++ I got & python 2.7. OS: W8 Single Language (spanish).

**Comment by fperegrinvs** [comment]
@Xzandro I was comparing 0.101 with 0.99.5 https://github.com/lstern/SWProxy-plugins/compare/0.99.5Q...0.101 and saw that swarfarm plugin included some initialization code.  I'm unable to reproduce the bug so I have to guess :D 

@tvcat  @Gesshoku01  try to remove the swaglogger plugin (deleting swaglogger files in the plugin folder)

**Comment by tvcat** [comment]
@lstern done, still the same error message
it looks like the program cant extract data to the temp foder

**Comment by IronChroni** [comment]
I'm having the same issue. Previous version including v0.100 work.
I do see what you mean @tvcat because I don't even see a blimp happen in Temp.
Perms on Temp for the user is full control for the user system and admins, so not sure why.

**Comment by fperegrinvs** [comment]
can you test the new package that I have just created: SWProxy-windows-4.zip @ release 0.102

**Comment by tvcat** [comment]
@lstern thanks, its all good now

**Comment by fperegrinvs** [comment]
thanks! @tvcat

**Comment by Gesshoku01** [comment]
@lstern New version working perfectly. Thank you very much, keep the awesome work n.n
