### ISSUE TITLE
Past two versions cause a DLL issue windows 7

### ISSUE THREAD

**Issue by IronChroni** [lstern/SWProxy-plugins#69]
Just want to say that v0.100 works fine

But everything since up to v0.102 does not, when dragged onto an admin CMD:
`C:\Windows\system32>C:\Users\User1\Downloads\SWProxy-windows-3\SWProxy.exe
Error loading Python DLL: C:\Users\User1\AppData\Local\Temp\_MEI24922\python27.dll <error code 14001>`

Tested from things I've found online - this is not a permissions issue on my side.

**Comment by fperegrinvs** [comment]
fixed with last build (check #68 )
