### ISSUE TITLE
Update readme with instruction on how to install the plugins

### ISSUE THREAD

**Issue by fperegrinvs** [lstern/SWProxy-plugins#7]

**Comment by daniellhotka** [comment]
I can work on one, maybe with a video as well, but we currently have a bigger problem. As of patch 2.0.7 the proxy no longer picks up any requests, I presume they have changed the encryption key.

**Comment by fperegrinvs** [comment]
Yes they changed the encryption key

**Comment by daniellhotka** [comment]
now that the Proxy is fixed I was planning on making a short video how to install the plugins. Is there anything in particular you would like included or excluded?

**Comment by fperegrinvs** [comment]
Great idea. Just make sure to cover all minor steps showing the config and
the log files. Let me know when you have the video ready so I can help
spreading it.

**Comment by daniellhotka** [comment]
Here's the video, not sure if you want to add it to the superpost on reddit that got stickied or create a new post and reference it.
https://www.youtube.com/watch?v=T4zI6HViV9g

**Comment by fperegrinvs** [comment]
Nice vídeo, thanks. Added to the main post. As few people know about the
plugins, I guess you should also post video as a separate post

**Comment by fperegrinvs** [comment]
I've also added this link in the Readme file and changed the default
full-log setting to false
