### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by RaphaelDDL** [lstern/SWProxy-plugins#78]
Hi there,

Last time I used SWProxy was the `.100` one on Yosemite, I believe two months ago. After I upgraded to Sierra this month, trying to run SWProxy ends on `Segmentation fault: 11`, even though I didn't touch the folder.

I downloaded the `.102b`, ran `python setup.py install` and still same thing when running `python SWProxy.py`:

        INFO:SWProxy:SwarfarmLogger - Retrieving list of accepted log types from SWARFARM...
        INFO:SWProxy:SwarfarmLogger - Looking for the following commands to log:
        GetBlackMarketList, BattleRiftDungeonResult, BattleRiftOfWorldsRaidResult, BattleWorldBossStart, BattleScenarioResult, SummonUnit, BattleRiftOfWorldsRaidStart, BattleDungeonResult, DoRandomWishItem, BattleScenarioStart, BuyShopItem, BattleWorldBossResult
        ########################################
        # SWParser v0.101-Plugins - Summoners War Proxy # 
        ########################################
          Written by:
            KaKaRoTo

          Authors:
            Youness Alaoui
            Leonardo Stern
            Azrethos

          Plugins:
            Generate Friend Swarfarm Data
            World Boss Logger
            Guidwar Summary Logger
            Raid Logger
            Trial of Ascension Logger
            Summon Logger
            Guild Battle Logger
            Recruit Evaluator
            SWARFARM Logger
            Swag Logger
            Arena Logger
            Live Optimizer
            Full Logger
            Google Sheets Writer
            Runs Logger

        Licensed under LGPLv3 and available at: 
          https://github.com/kakaroto/SWProxy

        Segmentation fault: 11

I also get the following error window:

![image](https://cloud.githubusercontent.com/assets/1087109/23581565/ec72e69a-00f4-11e7-9ac3-bed538177c56.png)

Reinstalling Python (v2.7.13, with `brew reinstall python`) and reinstalling deps (`sudo -H easy_install pycrypto dpkt yapsy`) didn't work either. Google search just pointed me to 10.9.X issues on python, which is not applicable to 10.12.X

So it's something on the code which looks incompatible with Sierra. Any ideas what could it be? 

Thanks.

**Comment by PeteAndersen** [comment]
Unfortunately I don't think any of us have macs to test with. We can still try to debug it though. Can you try running the proxy without any plugins installed? If it works, add the plugins back one by one to see if we can narrow it down. 

If the proxy doesn't work without plugins, does the upstream repo work? https://github.com/kakaroto/SWProxy/releases/latest

**Comment by RaphaelDDL** [comment]
I downloaded the upstream and tried to run `python SWProxy.py` and same thing.. Dies with 11.
In fact, the upstream version was the one I was using couple months ago (as I mentioned in OP).

Just to make sure, I even commented L8 `from SWPlugin import *` and L110-111. I even tried to install python3 just to test but as expected, syntax errors broke the script before running. 

After re-reading the call stack, it was crashing on `PyQt4.QtCore`, so I tried without the gui (`-g` flag) and it didn't crash and printed the IP:port. I'm at work right now so I can't test if is indeed working, but seems the one who broke when upgrading to Sierra wasn't the proxy per se, but the GUI.

I have latest pyqt (`4.11.4`) therefore gui code and/or `pytq` on Sierra is broken :(

Should I report that to upstream or is that something you guys look into to? (since I guess we think GUI is a plugin)

**Comment by RaphaelDDL** [comment]
Okay, so after second thoughts, I tried:

    brew install pyqt
    Warning: homebrew/boneyard/pyqt-4.11.4 already installed

Which is ok, but then I thought about dependencies, so I did `brew reinstall pyqt`. It redownloaded all the stuff (qt5 `5.8.0_1.sierra`) and guess what, I got an error by the end:

    Error: pyqt was moved to homebrew-boneyard because it has unfixable issues.
    Please do not file any issues about this. Sorry!

Checking brew's https://github.com/Homebrew/homebrew-core/issues/1705 showed this: `* pyqt - Lost cause. Already have PyQt5 for Qt5 support.`. Guess `pyqt` is broken for good on Sierra lol. 

I installed the other brew formula, `pyqt5` (which downloads `qt@5.7-5.7.1`)  but SWProxy fails to import PyQt. I tried  changing `PyQt4` import references to `PyQt` or `PyQt5` on gui.py, MainWndow.py and SWProxy.py but ondy difference was that now it falls on `except` rather than crashing, which means the import is wrong.

Do you know how to make the changes in order to test on pyqt5? If works, maybe would be good to use https://github.com/spyder-ide/qtpy in order to use pyqt5 on sierra and qt4 on lower (and other systems), or just entirely move to qt5 :P
