### ISSUE TITLE
Capture raid drops in the run logger

### ISSUE THREAD

**Issue by nighthound** [lstern/SWProxy-plugins#9]

**Comment by daniellhotka** [comment]
I'm working on implementing that as we speak, it's a whole separate request/response design so it might take me a few days. Might release as a separate plugin as the info it provides is vastly different to normal runs and condensing it into the same spreadsheet might not be the best way to use the information.

Other than the obvious: raid level - time - win/lose - drops (for all 3 people)
What of the following information do you think would be useful?
- damage contribution of each person
- dead/alive status of player's monsters (including teammates) 
- team rosters for each player (inc lvl)

**Comment by fperegrinvs** [comment]
Hey Ani. I have implemented some code to manage grindstones/enchament
https://github.com/kakaroto/SWProxy/issues/45

**Comment by daniellhotka** [comment]
Was just starting to pour over the code, that reference narrows it down a bit :) 
Any thoughts on the information it should contain?

**Comment by fperegrinvs** [comment]
level, Drop, runtime and maybe raidmates. Including teams is not that
useful IMO

**Comment by nighthound** [comment]
Would it make sense to have the Run Logger just parse the level, win/lose, runtime, and drops? And perhaps have a separate Raid Logger to include the full details that can be enabled separately if one is interested in that information. That way loot drops from scenarios, dungeons, raids can all be collated in a single file rather than spread over two separate logs.

**Comment by daniellhotka** [comment]
I've just uploaded my first working attempt at the raid logger, for now it's separate, and I'll probably try to merge it later. 
I expect it to be able to log everything correctly except shapeshifting stones as I have never seen them drop in raids lol. Despite this it should dump some info, if this occurs please forward the dump and I can patch it quickly.
